# Generated by Django 4.0 on 2021-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.CharField(max_length=500),
        ),
    ]
