# Generated by Django 4.1.1 on 2022-09-27 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ip_address', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Cancelled'), (3, 'Failed')], default=0)),
                ('payment_method', models.SmallIntegerField(choices=[(0, 'Paypal'), (1, 'BillPlz')])),
                ('bill_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('slug', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
                ('page_type', models.IntegerField(choices=[(0, 'Privacy Policy'), (1, 'Terms and Condition'), (2, 'About Us'), (3, 'General')])),
                ('is_active', models.BooleanField(default=0)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_attachment', to='coreapp.document')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_thumbnail', to='coreapp.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('site_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('short_desc', models.TextField(max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('twilio_account', models.CharField(max_length=100)),
                ('twilio_token', models.CharField(max_length=100)),
                ('twilio_number', models.CharField(max_length=100)),
                ('billplz_token', models.CharField(max_length=100)),
                ('billplz_signature', models.CharField(max_length=100)),
                ('billplz_collection', models.CharField(max_length=100)),
                ('paypal_client_id', models.CharField(max_length=100)),
                ('paypal_client_secret', models.CharField(max_length=100)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
